{{- if .Values.rbac.create }}
apiVersion: v1
data:
  accesskey: {{ .Values.configurations.credentials.accessKey | b64enc }}
  secretkey: dontcare
kind: Secret
metadata:
  name: v3io-webapi-secret
  namespace: {{ .Release.Namespace }}
  labels:
    component: argo
{{ include "pipelines.commonLabels" . | indent 4 }}
type: Opaque
{{- end }}
