{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo
  namespace: {{ .Release.Namespace }}
  labels:
    component: argo
{{ include "pipelines.commonLabels" . | indent 4 }}
{{- end }}
