{{- if .Values.deployment.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mpi-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "mpi-operator.name" . }}
    chart: {{ template "mpi-operator.chart" . }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpi-operator
  template:
    metadata:
      labels:
        app: mpi-operator
    spec:
      serviceAccountName: mpi-operator
      containers:
      - name: mpi-operator
        image: "{{ .Values.image.deployment.repository }}:{{ .Values.image.deployment.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: [
          "-alsologtostderr",
          "--kubectl-delivery-image",
          "{{ .Values.image.kubectl-delivery.repository }}:{{ .Values.image.kubectl-delivery.tag }}"
        ]
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
{{- end }}
