{{- if .Values.deployment.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mpi-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "mpi-operator.name" . }}
    chart: {{ template "mpi-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ template "mpi-operator.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "mpi-operator.name" . }}
        chart: {{ template "mpi-operator.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        component: mpi-operator
    spec:
      serviceAccountName: {{ template "mpi-operator.serviceAccountName" . }}
      containers:
      - name: {{ template "mpi-operator.fullname" . }}
        image: "{{ .Values.image.deployment.repository }}:{{ .Values.image.deployment.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: [
          "-alsologtostderr",
          "--kubectl-delivery-image",
          "{{ .Values.image.kubectlDelivery.repository }}:{{ .Values.image.kubectlDelivery.tag }}"
        ]
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- end }}
