{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-runner
  namespace: {{ .Release.Namespace }}
  labels:
    component: pipeline-runner
{{ include "pipelines.commonLabels" . | indent 4 }}
{{- end }}
