{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "label-studio.roleName" . }}
  labels:
    {{ include "label-studio.common.labels" . | nindent 4 }}
rules: []
{{- end }}
