{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "label-studio.serviceAccountName" . }}
  labels:
    {{- include "label-studio.common.labels" . | nindent 4 }}
{{- end -}}
