{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ml-pipeline
  namespace: {{ .Release.Namespace }}
  labels:
    component: ml-pipeline
{{ include "pipelines.commonLabels" . | indent 4 }}
{{- end }}
