# nameOverride:
# fullnameOverride:

deployment:
  create: true
  project:
    name: "my_project"
    initialize: true
    forceInitialize: false
  image:
    repository: "heartexlabs/label-studio"
    tag: 0.8.2
    pullPolicy: IfNotPresent

  readinessProbe:
    httpGet:
      path: /api/health
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 10

  livenessProbe:
    httpGet:
      path: /api/health
      port: 8080
    initialDelaySeconds: 60
    timeoutSeconds: 30
    periodSeconds: 10
    failureThreshold: 10

service:
  type: ClusterIP
  port: 8080
  # nodePort: 30030

rbac:
  create: true
  # serviceAccountName:
  # roleName:


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
