{{- if .Values.rbac.create }}
apiVersion: v1
kind: Service
metadata:
  name: ml-pipeline-visualizationserver
  namespace: {{ .Release.Namespace }}
  labels:
    component: ml-pipeline-visualizationserver
{{ include "pipelines.commonLabels" . | indent 4 }}
spec:
  ports:
  - name: http
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    component: ml-pipeline-visualizationserver
{{ include "pipelines.commonLabels" . | indent 4 }}
{{- end }}
