{{- if .Values.crd.create }}
apiVersion: {{ template "crd.apiVersion" . }}
kind: CustomResourceDefinition
metadata:
  name: workflows.argoproj.io
  labels:
    component: crd
{{ include "pipelines.commonLabels" . | indent 4 }}
spec:
  group: argoproj.io
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
  scope: Namespaced
  names:
    kind: Workflow
    plural: workflows
    shortNames:
    - wf
{{- end }}
