{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: ml-pipeline-persistenceagent-binding
  namespace: {{ .Release.Namespace }}
  labels:
    component: ml-pipeline-persistenceagent
{{ include "pipelines.commonLabels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ml-pipeline-persistenceagent-role
subjects:
- kind: ServiceAccount
  name: ml-pipeline-persistenceagent
  namespace: {{ .Release.Namespace }}
{{- end }}
