{{- if .Values.nfsPv.create -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-nfs-server-provisioner
  labels:
    app.kubernetes.io/name: {{ template "open-mlops.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  storageClassName: "open-mlops-manual"
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp/{{ template "open-mlops.fullname" . }}
{{- end -}}
