dependencies:
- name: nuclio
  version: "0.7.18"
  repository: "https://nuclio.github.io/nuclio/charts"
- name: mlrun
  version: "0.5.14"
  repository: "https://v3io.github.io/helm-charts/stable"
- name: nfs-server-provisioner
  version: "1.1.1"
  repository: "https://charts.helm.sh/stable"
- name: mpi-operator
  version: "0.3.3"
  repository: "https://v3io.github.io/helm-charts/stable"
