# We use global values scope to multiplex the docker-registry details to both mlrun and nuclio
global:
  externalAddress: localhost
  registry:
    url: mustprovide
    secretName: mustprovide

nuclio:

  # coupled with mlrun.nuclio.dashboardName template in mlrun chart
  fullnameOverride: nuclio
  controller:
    enabled: true
    image:
      tag: 1.5.16-amd64
  dashboard:
    enabled: true
    nodePort: 30060
    image:
      tag: 1.5.16-amd64
  autoscaler:
    enabled: false
  dlx:
    enabled: false
  rbac:
    create: true
    crdAccessMode: cluster
  crd:
    create: true
  platform:
    logger:
      sinks:
        myStdoutLoggerSink:
          kind: stdout
          attributes:
            encoding: console
            timeFieldName: time
            timeFieldEncoding: iso8601
      system:
      - level: debug
        sink: myStdoutLoggerSink
      functions:
      - level: debug
        sink: myStdoutLoggerSink
mlrun:
  fullnameOverride: mlrun
  nuclio:
    mode: enabled
    uiURL: http://localhost:30060
  rbac:
    create: true
  v3io:
    enabled: false
  api:
    fullnameOverride: mlrun-api
    image:
      tag: 0.6.0
    volumes:
      storageOverride:
        persistentVolumeClaim:
          claimName: mlrun-pvc
  ui:
    fullnameOverride: mlrun-ui
    service:
      type: NodePort
      nodePort: 30050
    image:
      tag: 0.6.0

# mlrun persistency resources creation can be disabled if the user would like to provide their own PVC
mlrunPersistency:
  pv:
    create: true
  pvc:
    create: true

jupyterNotebook:
  service:
    nodePort: 30040
  image:
    repository: quay.io/mlrun/jupyter
    tag: 0.6.0
    pullPolicy: IfNotPresent
  # use this to override mlrunUIURL, by default it will auto resolve to externalAddress and node port
  # mlrunUIURL:

mpi-operator:
  nameOverride: mpi-operator
  crd:
    create: true
  rbac:
    clusterResources:
      create: true
    namespaced:
      create: true
  deployment:
    create: true

## customize PV spec used for nfs-server provisioner
## ref: https://kubernetes.io/docs/concepts/storage/persistent-volumes/
##
nfsPv:
  create: false
  specOverride: {}

nfs-server-provisioner:
  nameOverride: nfs-server-provisioner
  persistence:
    enabled: false
    storageClass: "mlrun-kit-nfs"
    size: 5Gi
