{{- if .Values.controller.crd.create }}

apiVersion: {{ template "crd.apiVersion" . }}
kind: CustomResourceDefinition
metadata:
  name: iguazioapigateways.iguazio.com
  labels:
    app: {{ template "provazio.name" . }}
    chart: {{ template "provazio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: crd
spec:
  group: iguazio.com
  names:
    kind: IguazioAPIGateway
    plural: iguazioapigateways
    singular: iguazioapigateway
  scope: Namespaced
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
{{- end }}
