apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-notebook
  labels:
    app.kubernetes.io/component: jupyter-notebook
    app.kubernetes.io/name: open-mlops
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: jupyter-notebook
      app.kubernetes.io/name: open-mlops
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: jupyter-notebook
        app.kubernetes.io/name: open-mlops
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: jupyter-notebook
        image: mlrun/jupyter:0.5.2
        env:
        - name: MLRUN_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: JUPYTER_ENABLE_LAB
          value: "yes"
        - name: MLRUN_DBPATH
          value: "http://mlrun-api:8080"
        - name: MLRUN_ARTIFACT_PATH
          value: "/home/jovyan/data"
        volumeMounts:
        - mountPath: /home/jovyan/data
          name: notebooks
        ports:
        - containerPort: 8888
        command: ["start-notebook.sh"]
        args:
        - --ip="0.0.0.0"
        - --port=8888
        - --NotebookApp.token=''
        - --NotebookApp.password=''
        - --NotebookApp.default_url="/lab"
      volumes:
      - name: notebooks
        persistentVolumeClaim:
          claimName: nfsvol
