apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfsvol
  labels:
    app.kubernetes.io/name: open-mlops
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  storageClassName: "nfs"    #the installed Chart just created this
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
