kind: Service
apiVersion: v1
metadata:
  name: jupyter-notebook
  labels:
    app.kubernetes.io/component: jupyter-notebook
    app.kubernetes.io/name: open-mlops
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}

spec:
  type: NodePort
  selector:
    app: jupyter-notebook
  ports:
  - protocol: TCP
    nodePort: 30040
    port: 8888
    targetPort: 8888
