{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ml-pipeline-viewer-crd-service-account
  namespace: {{ .Release.Namespace }}
  labels:
    component: ml-pipeline-viewer-crd
{{ include "pipelines.commonLabels" . | indent 4 }}
{{- end }}
