{{/*kind: Service*/}}
{{/*apiVersion: v1*/}}
{{/*metadata:*/}}
{{/*  name: {{ template "mlrun-os.nuclio.dashboardFullname" . }}*/}}
{{/*  labels:*/}}
{{/*    app.kubernetes.io/component: nuclio-nodePort*/}}
{{/*    app.kubernetes.io/name: {{ template "mlrun-os.name" . }}*/}}
{{/*    app.kubernetes.io/instance: {{ .Release.Name }}*/}}
{{/*    app.kubernetes.io/managed-by: {{ .Release.Service }}*/}}
{{/*    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}*/}}

{{/*spec:*/}}
{{/*  type: NodePort*/}}
{{/*  selector:*/}}
{{/*    app: nuclio*/}}
{{/*    nuclio.io/app: dashboard*/}}
{{/*    nuclio.io/class: service*/}}
{{/*    nuclio.io/name: {{ template "mlrun-os.nuclio.dashboardFullname" . }}*/}}
{{/*    release: {{ .Release.Name }}*/}}
{{/*  ports:*/}}
{{/*  - protocol: TCP*/}}
{{/*    nodePort: {{ .Values.jupyterNotebook.service.nodePort }}*/}}
{{/*    port: 8888*/}}
{{/*    targetPort: 8888*/}}
