apiVersion: v1
appVersion: ">=0.2.1"
description: Kubeflow MPI job operator
name: mpi-operator
version: 0.0.1
home: https://iguazio.com
icon: https://www.iguazio.com/wp-content/uploads/2017/09/iguazio_logo_2017_w_c.png
sources:
  - https://github.com/kubeflow/mpi-operator
maintainers:
  - name: odedm
    email: odedm@iguazio.com
