{{- if .Values.nfsPv.create -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-nfs-server-provisioner
  labels:
    app.kubernetes.io/name: {{ template "mlrun-kit.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  storageClassName: {{ index .Values "nfs-server-provisioner" "persistence" "storageClass" }}
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /tmp/{{ template "mlrun-kit.fullname" . }}-nfs
{{- end -}}
