{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipelines-application-manager-role
  namespace: {{ .Release.Namespace }}
  labels:
    component: application-controller
{{ include "pipelines.commonLabels" . | indent 4 }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - update
  - patch
  - watch
- apiGroups:
  - app.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
{{- end }}
