{{- if .Values.deployment.create }}
apiVersion: v1
kind: Service
metadata:
  name: pipelines-controller-manager-service
  namespace: {{ .Release.Namespace }}
  labels:
    component: application-controller
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
{{ include "pipelines.commonLabels" . | indent 4 }}
spec:
  ports:
  - port: 443
  selector:
    component: application-controller
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
{{ include "pipelines.commonLabels" . | indent 4 }}
{{- end }}
