{{- if .Values.jupyterNotebook.persistency.pvc.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "mlrun-kit.jupyter-pvc.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "mlrun-kit.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
{{ toYaml .Values.jupyterNotebook.persistency.pvc.spec | indent 2 }}
{{- end }}