{{- if .Values.deployment.create }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: metadata-envoy
  labels:
    component: metadata-envoy
{{ include "pipelines.commonLabels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: metadata-envoy
  template:
    metadata:
      labels:
        component: metadata-envoy
{{ include "pipelines.commonLabels" . | indent 8 }}
    spec:
      containers:
      - name: container
        image: gcr.io/ml-pipeline/envoy:initial
        ports:
        - name: md-envoy
          containerPort: 9090
        - name: envoy-admin
          containerPort: 9901
{{- end }}
