{{- if .Values.deployment.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: metadata-mysql-configmap
  labels:
    component: metadata-server
{{ include "pipelines.commonLabels" . | indent 4 }}
data:
  MYSQL_DATABASE: "metadb"
  MYSQL_HOST: "mysql"
  MYSQL_PORT: "3306"
  MYSQL_USER: "root"
{{- end }}
