name: CI

on: [push, pull_request]

env:
  HELM_REPO: "https://get.helm.sh"
  HELM_BIN: "helm-v3.2.0-linux-amd64.tar.gz"

jobs:

  test:
    name: Test charts
    runs-on: ubuntu-latest
    steps:

    # we need to control kubectl version, because newer versions (come pre-installed) change the linting rules of
    # of helm w.r.t deprecated resource kinds
    - name: Install kubectl 1.15.5
      run: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.15.5/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
        kubectl version --clienl

    - name: Install Helm
      run: |
        wget -q ${HELM_REPO}/${HELM_BIN}
        tar xzvf ${HELM_BIN}
        PATH=$(pwd)/linux-amd64/:$PATH
        helm repo add stable https://kubernetes-charts.storage.googleapis.com
        helm repo add nuclio https://nuclio.github.io/nuclio/charts
        helm repo add v3io-stable https://v3io.github.io/helm-charts/stable

    - uses: actions/checkout@v2

    - name: Test stable
      run: make stable

    - name: Test demo
      run: make demo
