{{- if .Values.rbac.create }}
apiVersion: v1
kind: Service
metadata:
  name: ml-pipeline-ui
  namespace: {{ .Release.Namespace }}
  labels:
    component: ml-pipeline-ui
{{ include "pipelines.commonLabels" . | indent 4 }}
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    component: ml-pipeline-ui
{{ include "pipelines.commonLabels" . | indent 4 }}
{{- end }}
