dependencies:
- name: nuclio
  version: "0.6.9"
  repository: "https://nuclio.github.io/nuclio/charts"
- name: mlrun
  version: "0.4.0"
  repository: "https://v3io.github.io/helm-charts/stable"
- name: jupyterhub
  version: "0.9.0"
  repository: "https://jupyterhub.github.io/helm-chart/"
- name: nfs-server-provisioner
  version: "1.1.1"
  repository: "https://kubernetes-charts.storage.googleapis.com"
- name: mpi-operator
  version: "0.2.1"
  repository: "https://v3io.github.io/helm-charts/stable"
