nuclio:
  nameOverride: nuclio
  controller:
    enabled: true
  dashboard:
    enabled: true
  autoscaler:
    enabled: false
  dlx:
    enabled: false
  rbac:
    create: true
    crdAccessMode: cluster
  crd:
    create: true
  platform:
    logger:
      sinks:
        myStdoutLoggerSink:
          kind: stdout
          attributes:
            encoding: console
            timeFieldName: time
            timeFieldEncoding: iso8601
      system:
      - level: debug
        sink: myStdoutLoggerSink
      functions:
      - level: debug
        sink: myStdoutLoggerSink
mlrun:
  nameOverride: mlrun
  rbac:
    create: true
  defaultDockerRegistryURL:

jupyterNotebook:
  service:
    nodePort: 30040
  image:
    repository: mlrun/jupyter
    tag: 0.5.2
    pullPolicy: IfNotPresent

mpi-operator:
  nameOverride: mpi-operator
  crd:
    create: true
  rbac:
    clusterResources:
      create: true
    namespaced:
      create: true
  deployment:
    create: true

## Customize PV spec used for nfs-server provisioner
## ref: https://kubernetes.io/docs/concepts/storage/persistent-volumes/
##
nfsPv:
  create: true
  specOverride:

nfs-server-provisioner:
  nameOverride: nfs-server-provisioner
  persistence:
    enabled: true
    storageClass: "open-mlops-manual"
    size: 5Gi

  storageClass:
    defaultClass: true
