nuclio:
  controller:
    enabled: true
  dashboard:
    enabled: true
  autoscaler:
    enabled: false
  dlx:
    enabled: false
  rbac:
    create: true
    crdAccessMode: cluster
  crd:
    create: true
  platform:
    logger:
      sinks:
        myStdoutLoggerSink:
          kind: stdout
          attributes:
            encoding: console
            timeFieldName: time
            timeFieldEncoding: iso8601
      system:
      - level: debug
        sink: myStdoutLoggerSink
      functions:
      - level: debug
        sink: myStdoutLoggerSink

mlrun:
  rbac:
    create: true
  defaultDockerRegistryURL:

mpi-operator:
  crd:
    create: true
  rbac:
    clusterResources:
      create: true
    namespaced:
      create: true
  deployment:
    create: true


nfs-server-provisioner:
  persistence:
    enabled: true
    storageClass: "-"
    size: 5Gi

  storageClass:
    defaultClass: true

juypterhub:
